#!/bin/sh
set -e -x

trap exit TERM INT

if echo ${DEST_IP} | grep -Eq ":" 
then
    echo 1 > /proc/sys/net/ipv6/conf/all/forwarding || true
    if [ `cat /proc/sys/net/ipv6/conf/all/forwarding` != 1 ]; then
        exit 1
    fi
    ip6tables -t nat -I PREROUTING ! -s ${DEST_IP} -p ${DEST_PROTO} --dport ${SRC_PORT} -j DNAT --to ${DEST_IP}:${DEST_PORT}
    ip6tables -t nat -I POSTROUTING -d ${DEST_IP} -p ${DEST_PROTO} -j MASQUERADE
else
    echo 1 > /proc/sys/net/ipv4/ip_forward || true
    if [ `cat /proc/sys/net/ipv4/ip_forward` != 1 ]; then
        exit 1
    fi
    iptables -t nat -I PREROUTING ! -s ${DEST_IP}/32 -p ${DEST_PROTO} --dport ${SRC_PORT} -j DNAT --to ${DEST_IP}:${DEST_PORT}
    iptables -t nat -I POSTROUTING -d ${DEST_IP}/32 -p ${DEST_PROTO} -j MASQUERADE
fi

if [ ! -e /pause ]; then
    mkfifo /pause
fi
</pause
